/*
 * This code was generated by ojc.
 */
/*
 * Simple.java
 *
 * comments here.
 *
 * @author   Michiaki Tatsubori
 * @version  %VERSION% %DATE%
 * @see      java.lang.Object
 *
 * COPYRIGHT 1998 by Michiaki Tatsubori, ALL RIGHTS RESERVED.
 */
package examples.syntax;


import java.awt.Panel;
import java.util.*;
import java.io.PrintStream;


public class Test extends Panel
{

    private int iii = 0;

    private Vector v;

    private Test n = null;

    private String str = "string";

    private static final String DEF = "<default>";

    public Test()
    {
        super();
    }

    /**
     * @param  
     * @return  
     * @exception  
     * @see java.lang.Object
     */
    public static void main( String[] args )
    {}

    public String toString()
    {
        if (n == null) {
            return str;
        }
        return str + n;
    }

    public void hoge()
        throws Exception
    {}

    public void hoge1()
    {}

    public void hoge2()
    {}

    public void hoge2( String[] args )
    {}

    public void f()
    {
        System.out.println( "Hello" );
    }

    public void f1()
    {
        System.out.println( "Hello" );
    }

    public void f2()
    {
        System.out.println( "Hello" );
    }

    public void f3()
    {
        System.out.println( "Hello" );
    }

    public void g1()
    {}

    public void g2()
    {}

}
