/*
 * This code was generated by ojc.
 */
package examples.bca;


import java.io.PrintStream;


public class Test2
{

    public void write( PrintStream out )
    {
        out.println( "Hello" );
    }

}
