/*
 * This code was generated by ojc.
 */
package examples.adapter;


import java.util.Enumeration;


public interface Stack
{

    public int size();

    public boolean isEmpty();

    public java.util.Enumeration elements();

    public java.lang.Object[] toArray();

    public int hashCode();

    public void push( java.lang.Object o );

    public java.lang.Object pop();

    public java.lang.Object peek();

}
