package packfld;

/*
 * This code was generated by ojc.
 */
public class Test {
	static final int HSIZE = 50000;
}

class A {
	public static void main(java.lang.String[] args) {
		System.err.println(Test.HSIZE);
	}
}
