/*
 * This code was generated by ojc.
 */
package examples.mixin;


public class TextboxWithUndo extends Textbox implements examples.mixin.Undo
{

    
    public void setText( java.lang.String oj_param0 )
    {
        return;
    }

    
    public void undo()
    {
        return;
    }

}
