/*
 * This code was generated by ojc.
 */
package examples.mixin;


public class Textbox extends java.awt.Component
{

    String text = null;

    /* ..... */
    public String getText()
    {
        return text;
    }

    public void setText( String s )
    {
        text = s;
    }

}
