/*
 * This code was generated by ojc.
 */
package examples.verbose2;


import java.awt.Panel;
import java.util.*;
import java.io.PrintStream;


public class Test extends Panel
{

    private int iii = 0;

    private Test n = null;

    private String str = "string";

    public Test()
    {
        super();
    }

    /**
     * @param  
     * @return  
     * @exception  
     * @see java.lang.Object
     */
    public static void main( String[] argv )
    {
        java.lang.System.out.println( "main is called." );
        PrintStream out = System.out;
        PrintStream error = java.lang.System.err;
        out.println( "Hello" + " " + "World" );
        Test n = new Test();
        java.lang.System.err.println( "done. " );
        Test test = new Test();
        test.hoge();
        test.foo();
    }

    public void hoge()
    {
        java.lang.System.out.println( "hoge is called." );
        Local l = new Local();
        System.out.println( l.foo );
        System.out.println( l.bar.str );
    }

    public Test( String str )
    {
        this.str = str;
        n = null;
    }

    public int foo()
    {
        java.lang.System.out.println( "foo is called." );
        return iii;
    }

    public String toString()
    {
        java.lang.System.out.println( "toString is called." );
        if (n == null) {
            return str;
        }
        return str + n;
    }

}


class Local
{

    String foo = null;

    Local2 bar = new Local2();

    public final String getFoo( Integer i )
    {
        java.lang.System.out.println( "getFoo is called." );
        return foo;
    }

}


class Local2
{

    String str = "" + "TEST";

}
