/*
 * This code was generated by ojc.
 */
/*
 * CopiedClass.oj
 *
 * @author   Michiaki Tatsubori
 * @see      java.lang.Object
 *
 * COPYRIGHT 1999 by Michiaki Tatsubori, ALL RIGHTS RESERVED.
 */
package examples.copy;


import openjava.mop.*;
import openjava.ptree.*;
import openjava.syntax.*;
import openjava.ptree.util.TypeNameQualifier;


public class CopiedClass extends OJClass
{

    /* overrides for translation */
    public void translateDefinition()
        throws MOPException
    {
        String newqname = getName() + "Shadow";
        OJClass shadow = makeCopy( newqname );
        OJSystem.addNewClass( shadow );
    }

    public CopiedClass( openjava.mop.Environment oj_param0, openjava.mop.OJClass oj_param1, openjava.ptree.ClassDeclaration oj_param2 )
    {
        super( oj_param0, oj_param1, oj_param2 );
    }

    public CopiedClass( java.lang.Class oj_param0, openjava.mop.MetaInfo oj_param1 )
    {
        super( oj_param0, oj_param1 );
    }

}
