/*
 * This code was generated by ojc.
 */
package examples.copy;


import java.awt.Panel;
import java.util.*;
import java.io.PrintStream;


public class Test extends Panel
{

    private int iii = 0;

    private Test n = null;

    private String str = "string";

    public Test()
    {
        super();
    }

    /**
     * @param  
     * @return  
     * @exception  
     * @see java.lang.Object
     */
    public static void main( String[] argv )
    {
        PrintStream out = System.out;
        PrintStream error = java.lang.System.err;
        out.println( "Hello" + " " + "World" );
        Test n = new Test();
        java.lang.System.err.println( "done. " );
        Test test = new Test();
        test.foo();
    }

    public Test( String str )
    {
        this.str = str;
        n = null;
    }

    public int foo()
    {
        return iii;
    }

    public String toString()
    {
        if (n == null) {
            return str;
        }
        return str + n;
    }

}
