/*
 * This code was generated by ojc.
 */

package examples.copy;


public class TestShadow extends java.awt.Panel
{

    private int iii = 0;

    private examples.copy.Test n = null;

    private java.lang.String str = "string";

    public TestShadow()
    {
        super();
    }

    /**
     * @param  
     * @return  
     * @exception  
     * @see java.lang.Object
     */
    public static void main( java.lang.String[] argv )
    {
        java.io.PrintStream out = java.lang.System.out;
        java.io.PrintStream error = java.lang.System.err;
        out.println( "Hello" + " " + "World" );
        examples.copy.Test n = new examples.copy.Test();
        java.lang.System.err.println( "done. " );
        examples.copy.Test test = new examples.copy.Test();
        test.foo();
    }

    public TestShadow( java.lang.String str )
    {
        this.str = str;
        n = null;
    }

    public int foo()
    {
        return iii;
    }

    public java.lang.String toString()
    {
        if (n == null) {
            return str;
        }
        return str + n;
    }

}
