/*
 * This code was generated by ojc.
 */

package examples.facemake;



public interface TestFace
{

    
    public void print( java.awt.Graphics oj_param0 );

    
    public void layout();

    
    public void setLocation( java.awt.Point oj_param0 );

    
    public java.awt.Dimension getPreferredSize();

    
    public java.awt.Dimension getSize( java.awt.Dimension oj_param0 );

    
    public boolean isShowing();

    
    public void repaint( long oj_param0 );

    
    public java.awt.Point getLocationOnScreen();

    
    public void update( java.awt.Graphics oj_param0 );

    
    public java.awt.Dimension minimumSize();

    
    public int getHeight();

    
    public void reshape( int oj_param0, int oj_param1, int oj_param2, int oj_param3 );

    
    public java.awt.Insets insets();

    
    public boolean keyUp( java.awt.Event oj_param0, int oj_param1 );

    
    public void show();

    
    public boolean contains( java.awt.Point oj_param0 );

    
    public boolean action( java.awt.Event oj_param0, java.lang.Object oj_param1 );

    
    public boolean mouseDown( java.awt.Event oj_param0, int oj_param1, int oj_param2 );

    
    public void addMouseMotionListener( java.awt.event.MouseMotionListener oj_param0 );

    
    public boolean isEnabled();

    
    public void setFont( java.awt.Font oj_param0 );

    
    public boolean prepareImage( java.awt.Image oj_param0, int oj_param1, int oj_param2, java.awt.image.ImageObserver oj_param3 );

    
    public boolean mouseEnter( java.awt.Event oj_param0, int oj_param1, int oj_param2 );

    
    public void addFocusListener( java.awt.event.FocusListener oj_param0 );

    
    public void setBounds( java.awt.Rectangle oj_param0 );

    
    public boolean inside( int oj_param0, int oj_param1 );

    
    public void setBounds( int oj_param0, int oj_param1, int oj_param2, int oj_param3 );

    
    public float getAlignmentX();

    
    public boolean contains( int oj_param0, int oj_param1 );

    
    public java.awt.peer.ComponentPeer getPeer();

    
    public java.awt.Component[] getComponents();

    
    public java.awt.Component findComponentAt( int oj_param0, int oj_param1 );

    
    public void setComponentOrientation( java.awt.ComponentOrientation oj_param0 );

    
    public java.awt.Component getComponentAt( int oj_param0, int oj_param1 );

    
    public java.awt.Component getComponent( int oj_param0 );

    
    public void removeContainerListener( java.awt.event.ContainerListener oj_param0 );

    
    public void remove( int oj_param0 );

    
    public void remove( java.awt.MenuComponent oj_param0 );

    
    public java.awt.Cursor getCursor();

    
    public java.awt.Component getComponentAt( java.awt.Point oj_param0 );

    
    public void move( int oj_param0, int oj_param1 );

    
    public java.awt.Dimension preferredSize();

    
    public java.awt.Image createImage( int oj_param0, int oj_param1 );

    
    public void removeInputMethodListener( java.awt.event.InputMethodListener oj_param0 );

    
    public int getComponentCount();

    
    public void removeComponentListener( java.awt.event.ComponentListener oj_param0 );

    
    public void setForeground( java.awt.Color oj_param0 );

    
    public void addPropertyChangeListener( java.lang.String oj_param0, java.beans.PropertyChangeListener oj_param1 );

    
    public int foo();

    
    public void setLocale( java.util.Locale oj_param0 );

    
    public java.awt.Point getLocation( java.awt.Point oj_param0 );

    
    public void list( java.io.PrintStream oj_param0, int oj_param1 );

    
    public int checkImage( java.awt.Image oj_param0, java.awt.image.ImageObserver oj_param1 );

    
    public java.awt.Dimension size();

    
    public boolean isVisible();

    
    public java.awt.Dimension getMinimumSize();

    
    public void doLayout();

    
    public boolean gotFocus( java.awt.Event oj_param0, java.lang.Object oj_param1 );

    
    public void addInputMethodListener( java.awt.event.InputMethodListener oj_param0 );

    
    public int getY();

    
    public java.awt.Component add( java.awt.Component oj_param0, int oj_param1 );

    
    public boolean isOpaque();

    
    public boolean isValid();

    
    public void removeKeyListener( java.awt.event.KeyListener oj_param0 );

    
    public boolean isDisplayable();

    
    public void setName( java.lang.String oj_param0 );

    
    public java.awt.Toolkit getToolkit();

    
    public java.awt.ComponentOrientation getComponentOrientation();

    
    public void setLocation( int oj_param0, int oj_param1 );

    
    public void addNotify();

    
    public java.awt.Dimension getMaximumSize();

    
    public java.lang.String getName();

    
    public void setSize( int oj_param0, int oj_param1 );

    
    public void add( java.awt.PopupMenu oj_param0 );

    
    public void list( java.io.PrintWriter oj_param0 );

    
    public int countComponents();

    
    public java.awt.Point getLocation();

    
    public void resize( java.awt.Dimension oj_param0 );

    
    public java.util.Locale getLocale();

    
    public void removePropertyChangeListener( java.beans.PropertyChangeListener oj_param0 );

    
    public void resize( int oj_param0, int oj_param1 );

    
    public boolean mouseDrag( java.awt.Event oj_param0, int oj_param1, int oj_param2 );

    
    public java.awt.Point location();

    
    public java.awt.image.ColorModel getColorModel();

    
    public void removeNotify();

    
    public void repaint( long oj_param0, int oj_param1, int oj_param2, int oj_param3, int oj_param4 );

    
    public void removePropertyChangeListener( java.lang.String oj_param0, java.beans.PropertyChangeListener oj_param1 );

    
    public void removeMouseListener( java.awt.event.MouseListener oj_param0 );

    
    public int checkImage( java.awt.Image oj_param0, int oj_param1, int oj_param2, java.awt.image.ImageObserver oj_param3 );

    
    public void paintComponents( java.awt.Graphics oj_param0 );

    
    public void list();

    
    public void dispatchEvent( java.awt.AWTEvent oj_param0 );

    
    public java.lang.Object getTreeLock();

    
    public void printAll( java.awt.Graphics oj_param0 );

    
    public void nextFocus();

    
    public boolean mouseExit( java.awt.Event oj_param0, int oj_param1, int oj_param2 );

    
    public void addComponentListener( java.awt.event.ComponentListener oj_param0 );

    
    public void deliverEvent( java.awt.Event oj_param0 );

    
    public void requestFocus();

    
    public void disable();

    
    public void setEnabled( boolean oj_param0 );

    
    public void repaint();

    
    public void setVisible( boolean oj_param0 );

    
    public java.awt.FontMetrics getFontMetrics( java.awt.Font oj_param0 );

    
    public java.awt.Color getBackground();

    
    public java.awt.Rectangle getBounds();

    
    public void invalidate();

    
    public boolean hasFocus();

    
    public void show( boolean oj_param0 );

    
    public java.awt.Dimension getSize();

    
    public java.awt.Font getFont();

    
    public boolean mouseUp( java.awt.Event oj_param0, int oj_param1, int oj_param2 );

    
    public boolean imageUpdate( java.awt.Image oj_param0, int oj_param1, int oj_param2, int oj_param3, int oj_param4, int oj_param5 );

    
    public boolean prepareImage( java.awt.Image oj_param0, java.awt.image.ImageObserver oj_param1 );

    
    public java.awt.Image createImage( java.awt.image.ImageProducer oj_param0 );

    
    public void add( java.awt.Component oj_param0, java.lang.Object oj_param1, int oj_param2 );

    
    public int getX();

    
    public java.awt.Container getParent();

    
    public java.awt.dnd.DropTarget getDropTarget();

    
    public boolean lostFocus( java.awt.Event oj_param0, java.lang.Object oj_param1 );

    
    public void enable( boolean oj_param0 );

    
    public void addKeyListener( java.awt.event.KeyListener oj_param0 );

    
    public void setSize( java.awt.Dimension oj_param0 );

    
    public void paint( java.awt.Graphics oj_param0 );

    
    public java.awt.Rectangle getBounds( java.awt.Rectangle oj_param0 );

    
    public void removeFocusListener( java.awt.event.FocusListener oj_param0 );

    
    public void removeAll();

    
    public float getAlignmentY();

    
    public boolean isFocusTraversable();

    
    public void enable();

    
    public java.awt.Rectangle bounds();

    
    public java.awt.Component locate( int oj_param0, int oj_param1 );

    
    public java.awt.im.InputContext getInputContext();

    
    public boolean keyDown( java.awt.Event oj_param0, int oj_param1 );

    
    public void addPropertyChangeListener( java.beans.PropertyChangeListener oj_param0 );

    
    public java.awt.Component add( java.awt.Component oj_param0 );

    
    public void printComponents( java.awt.Graphics oj_param0 );

    
    public java.awt.LayoutManager getLayout();

    
    public void paintAll( java.awt.Graphics oj_param0 );

    
    public void addMouseListener( java.awt.event.MouseListener oj_param0 );

    
    public java.awt.Component add( java.lang.String oj_param0, java.awt.Component oj_param1 );

    
    public void add( java.awt.Component oj_param0, java.lang.Object oj_param1 );

    
    public void addContainerListener( java.awt.event.ContainerListener oj_param0 );

    
    public void hide();

    
    public void list( java.io.PrintStream oj_param0 );

    
    public void enableInputMethods( boolean oj_param0 );

    
    public void transferFocus();

    
    public java.awt.im.InputMethodRequests getInputMethodRequests();

    
    public java.awt.Insets getInsets();

    
    public void setCursor( java.awt.Cursor oj_param0 );

    
    public boolean mouseMove( java.awt.Event oj_param0, int oj_param1, int oj_param2 );

    
    public void setBackground( java.awt.Color oj_param0 );

    
    public void setDropTarget( java.awt.dnd.DropTarget oj_param0 );

    
    public boolean isLightweight();

    
    public void repaint( int oj_param0, int oj_param1, int oj_param2, int oj_param3 );

    
    public void remove( java.awt.Component oj_param0 );

    
    public boolean isAncestorOf( java.awt.Component oj_param0 );

    
    public boolean postEvent( java.awt.Event oj_param0 );

    
    public boolean isDoubleBuffered();

    
    public int getWidth();

    
    public java.awt.Component findComponentAt( java.awt.Point oj_param0 );

    
    public boolean handleEvent( java.awt.Event oj_param0 );

    
    public java.awt.Graphics getGraphics();

    
    public void validate();

    
    public java.awt.Color getForeground();

    
    public void list( java.io.PrintWriter oj_param0, int oj_param1 );

    
    public void removeMouseMotionListener( java.awt.event.MouseMotionListener oj_param0 );

    
    public void setLayout( java.awt.LayoutManager oj_param0 );

}
