/*
 * This code was generated by ojc.
 */
/*
 * Printer.java
 *
 */
package examples.order2;


import openjava.mop.*;


public class Printer extends openjava.mop.OJClass
{

    public void translateDefinition()
    {
        openjava.mop.OJClass base = getSuperclass();
        System.out.println( "I'm " + getName() + "." );
        System.out.println( getName() + " finished." );
    }

    public void translateDefinition0()
    {
        openjava.mop.OJClass base = getSuperclass();
        System.out.println( "I'm " + getName() + "." + "  " + "After You, " + base.getName() + "." );
        try {
            waitTranslation( base );
        } catch ( java.lang.Exception e ) {
            System.err.println( e.toString() );
        }
        System.out.println( getName() + " finished." );
    }

    public Printer( openjava.mop.Environment oj_param0, openjava.mop.OJClass oj_param1, openjava.ptree.ClassDeclaration oj_param2 )
    {
        super( oj_param0, oj_param1, oj_param2 );
    }

    public Printer( java.lang.Class oj_param0, openjava.mop.MetaInfo oj_param1 )
    {
        super( oj_param0, oj_param1 );
    }

}
