/*
 * This code was generated by ojc.
 */
package examples.order2;


public class Test extends examples.order2.E
{
}


class B extends examples.order2.A
{
}


class E extends examples.order2.D
{
}


class C extends examples.order2.B
{
}


class D extends examples.order2.C
{
}


class A extends java.lang.Object
{
}
