/*
 * This code was generated by ojc.
 */
/* quick implementation! */
package examples.autoimp;


import java.awt.event.*;


public class InnerTest
{

    public static void main( String[] args )
    {
        WindowListener tmp = new MyWindowListener();
    }

    static class MyWindowListener implements WindowListener
    {

        public void windowClosed( WindowEvent e )
        {
            System.exit( 0 );
        }

    }

}
