/*
 * This code was generated by ojc.
 */
/* quick implementation! */
package examples.autoimp;


import java.awt.event.*;


public class Test implements WindowListener
{

    public void windowClosed( WindowEvent e )
    {
        System.exit( 0 );
    }

    
    public void windowIconified( java.awt.event.WindowEvent oj_param0 )
    {
        return;
    }

    
    public void windowDeactivated( java.awt.event.WindowEvent oj_param0 )
    {
        return;
    }

    
    public void windowActivated( java.awt.event.WindowEvent oj_param0 )
    {
        return;
    }

    
    public void windowOpened( java.awt.event.WindowEvent oj_param0 )
    {
        return;
    }

    
    public void windowDeiconified( java.awt.event.WindowEvent oj_param0 )
    {
        return;
    }

    
    public void windowClosing( java.awt.event.WindowEvent oj_param0 )
    {
        return;
    }

}
