/*
 * This code was generated by ojc.
 */
package examples.print;


import openjava.mop.*;
import openjava.ptree.*;


public class MyClass extends OJClass
{

    public MyClass( Environment outer_env, OJClass declarer, ClassDeclaration ptree )
    {
        super( outer_env, declarer, ptree );
    }

    public MyClass( Class javaclass, MetaInfo minfo )
    {
        super( javaclass, minfo );
    }

    protected void pro()
    {}

    public void pub()
    {}

}
