/*
 * This code was generated by ojc.
 */
package examples.verbose;


public class Hello
{

    public static void main( java.lang.String[] argv )
    {
        java.lang.System.out.println( "public static void examples.verbose.Hello.main(java.lang.String[]) was called" );
        hello();
    }

    static void hello()
    {
        java.lang.System.out.println( "static void examples.verbose.Hello.hello() was called" );
        System.out.println( "Hello, world." );
    }

}
