/*
 * This code was generated by ojc.
 */
/*
 * Test.oj
 *
 * Apr 13, 1999  Michiaki Tatsubori
 */
package examples.freeargs;


import java.lang.Object;


/**
 * Just a test.
 */
public class Test
{

    /**
     * This is main method.
     */
    public static void main( java.lang.String[] args )
    {
        examples.freeargs.Collection c = new examples.freeargs.Collection();
        c.set( new java.lang.Object[]{ new java.lang.Integer( args.length ), args[0], args[1] } );
        c.add( new java.lang.Object[]{ new java.lang.Integer( args.length ), args[0], args[1] } );
        System.out.println( c.size() );
    }

}
